1.Creating Arrays

In [14]:
import numpy as np

zeros=np.zeros((3, 4))
ones=np.ones((3, 4))
identity=np.eye(3)
array=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ar=np.arange(0, 10, 2)
l=np.linspace(0, 1, 5)
r=np.random.rand(3, 4)
print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)
print("Array:\n", array)
print("Arange:\n", ar)
print("Linspace:\n", l)
print("Random Matrix:\n", r)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Arange:
 [0 2 4 6 8]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]
Random Matrix:
 [[0.06274657 0.55672159 0.60897614 0.10674332]
 [0.07171791 0.34758753 0.62195998 0.05883315]
 [0.12871002 0.48317775 0.16242808 0.99918747]]


There are many ways to create an numpy array like: an zeros array which contains of just zeros values, ones the same idea contains just ones values, we can create our own array and has the values i need, also an arange array i give it the start value, the end value and the jump value, a linspace array i give it the start value, end value and the number of item in the array, at least we have Random which give me random values between 0 and 1.

2.Array Attributes

In [3]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of m: ", m.shape)
print("Data type of m: ", m.dtype)

Shape of m:  (2, 3)
Data type of m:  int64


I check the shape and data type of the array. This helps me understand the attributes of the array before performing my operations.

3.Indexing & Slicing

In [6]:
print(m[1, 2])
print(m[0, :])

6
[1 2 3]


This cell practices numpy indexing and slicing to access individual elements, rows, columns, and parts of arrays

4.Vectorized Operations

In [12]:
print("Result adding m to m:\n", m+m)
print("Result adding 2 to m:\n", m+2)
print("Sum of all elements in m: ", np.sum(m))
print("Mean of all elements in m: ", np.mean(m))
print("Output of m more than 3:\n", m[m>3])

Result adding m to m:
 [[ 2  4  6]
 [ 8 10 12]]
Result adding 2 to m:
 [[3 4 5]
 [6 7 8]]
Sum of all elements in m:  21
Mean of all elements in m:  3.5
Output of m more than 3:
 [4 5 6]


I perform simple operations on the array and calculate the sum and mean. I also filter the values greater than 3 using boolean masking.

5.Broadcasting

In [13]:
row=[10, 20, 30]
arr=m+row
print("Result of adding row to m:\n", arr)
print("Output of m more than 18:\n", arr[arr>18])

Result of adding row to m:
 [[11 22 33]
 [14 25 36]]
Output of m more than 18:
 [22 33 25 36]


This example shows how broadcasting can be used to add a row of values to every row in the array. Finally, I display only the values greater than 18 to practice filtering the result.