1.Creating Arrays & 2.Array Attributes

In [3]:
import numpy as np
a=np.reshape(np.arange(1,17), (4,4))

print("Array a:\n", a)
print("Shape of a:", a.shape)
print("Data type of a:", a.dtype)

Array a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape of a: (4, 4)
Data type of a: int64


In this cell, I create a 4x4 numpy array with values from 1 to 16. also print its shape and data type to check that the array was created correctly before using it.

3.Indexing & Slicing

In [7]:
print("Second Column of a:", a[:,1])
print("Last Row of a:", a[-1,:])

Second Column of a: [ 2  6 10 14]
Last Row of a: [13 14 15 16]


This cell shows how to access specific parts of a numpy array.I selected the second column and the last row of the array.

4.Boolean Mask 

In [9]:
mask=a[a>a.mean()]
print("Mean of a:", a.mean())
print("Elements greater than the mean of a:", mask)

Mean of a: 8.5
Elements greater than the mean of a: [ 9 10 11 12 13 14 15 16]


I calculate the average value of the array and then use a boolean condition to display only the elements that are greater than the mean. We use it to filter data without using loops.

5.Broadcasting

In [10]:
row=np.array([10,20,30,40])
res=a+row
print("Result of adding row to a:\n", res)

res_manually=np.zeros((4,4), dtype=int)
for i in range(4):
    for j in range(4):
        res_manually[i,j]=a[i,j]+row[j]
print("Result of adding row to a (manually):\n", res_manually)

Result of adding row to a:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]
Result of adding row to a (manually):
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]


I add a 1D array to every row of the matrix using broadcasting. I repeat the same operation with nested loops to compare the two methods and verify that they produce the same results.