# Step 1 — Create a Dataset Matrixx

In [34]:
import numpy as np
x= np.array([
    [22, 4500, 2],
    [35, 7200, 8],
    [28, 5600, 4]
])

print("The matrix :\n",x)
print("The shape of matrix is :",x.shape)

The matrix :
 [[  22 4500    2]
 [  35 7200    8]
 [  28 5600    4]]
The shape of matrix is : (3, 3)


### Step 1: Represent Three Data Samples as a Matrix

Create a NumPy matrix containing three samples.

Each row represents one customer.

Each column represents one feature:

- Age
- Income
- Years of experience

# Step 2 — Dot Product

In [35]:
sample = x[0]

w = np.array([0.2, 0.003, 1.2])

manual = (sample[0]*w[0] +sample[1]*w[1] +sample[2]*w[2])

dot_numpy = np.dot(sample, w)

print("Manual:", manual)
print("NumPy:", dot_numpy)

Manual: 20.299999999999997
NumPy: 20.3


### Step 2: Compute the Dot Product

First, calculate the prediction manually.

Then verify the result using NumPy's np.dot() function.

# Step 3 — Matrix Multiplication

In [36]:
predictions = x @ w

print(predictions)

[20.3 38.2 27.2]


### Step 3: Predict All Samples at Once

Instead of calculating one prediction at a time, use matrix multiplication to compute predictions for all samples simultaneously.

# Step 4 — Shape Mismatch Error

In [37]:
wrong_w = np.array([0.2, 0.0003])

x @ wrong_w

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### Step 4: Understanding a Shape Mismatch Error

The weight vector below contains only two values, while each sample has three features.

Since the number of features does not match the number of weights, matrix multiplication cannot be performed.

To fix the error, the weight vector must contain one weight for every feature in the dataset.